import type { Post } from 'app/components/types/Post'

export const PROFILE_USERNAME = 'alexrivera'

const PROFILE_COMMENTS = [
  {
    id: 'pc1',
    username: 'julianparks',
    text: 'This palette is incredible.',
    timeAgo: '32m',
    likes: 12,
  },
  {
    id: 'pc2',
    username: 'mariamc',
    text: 'The texture here feels so tactile.',
    timeAgo: '1h',
    likes: 8,
    replies: [
      {
        id: 'pc2r1',
        username: 'alexrivera',
        text: 'Thanks! Shot it on film.',
        timeAgo: '45m',
        likes: 3,
        replies: [
          {
            id: 'pc2r1r1',
            username: 'mariamc',
            text: 'That grain makes so much sense now.',
            timeAgo: '30m',
            likes: 2,
          },
        ],
      },
    ],
  },
  {
    id: 'pc3',
    username: 'chasekim',
    text: 'Need the full set of these.',
    timeAgo: '2h',
    likes: 5,
  },
]

export const PROFILE_POSTS: Post[] = [
  {
    id: 1,
    image: 'https://picsum.photos/600/600?1',
    type: 'image',
    caption: 'New perspectives on design',
    likes: 2847,
    comments: 89,
    commentList: PROFILE_COMMENTS,
    timestamp: '2h ago',
  },
  {
    id: 2,
    image: 'https://picsum.photos/600/600?2',
    type: 'image',
    caption: 'Minimalist architecture',
    likes: 1923,
    comments: 54,
    commentList: PROFILE_COMMENTS,
    timestamp: '1d ago',
  },
  {
    id: 3,
    image: 'https://picsum.photos/600/600?3',
    type: 'video',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    caption: 'Studio late-night session',
    likes: 1580,
    comments: 32,
    commentList: PROFILE_COMMENTS,
    timestamp: '3h ago',
  },
  {
    id: 4,
    image: 'https://picsum.photos/600/600?4',
    type: 'carousel',
    images: [
      'https://picsum.photos/600/600?4',
      'https://picsum.photos/600/600?14',
      'https://picsum.photos/600/600?24',
    ],
    caption: 'Textures and tones',
    likes: 980,
    comments: 21,
    commentList: PROFILE_COMMENTS,
    timestamp: '5h ago',
  },
  {
    id: 5,
    image: 'https://picsum.photos/600/600?5',
    type: 'image',
    caption: 'Concrete poetry',
    likes: 2140,
    comments: 64,
    commentList: PROFILE_COMMENTS,
    timestamp: '8h ago',
  },
  {
    id: 6,
    image: 'https://picsum.photos/600/600?6',
    type: 'image',
    caption: 'Light and shadow study',
    likes: 1340,
    comments: 27,
    commentList: PROFILE_COMMENTS,
    timestamp: '12h ago',
  },
  {
    id: 7,
    image: 'https://picsum.photos/600/600?7',
    type: 'image',
    caption: 'Analog noise',
    likes: 890,
    comments: 18,
    commentList: PROFILE_COMMENTS,
    timestamp: '1d ago',
  },
  {
    id: 8,
    image: 'https://picsum.photos/600/600?8',
    type: 'carousel',
    images: [
      'https://picsum.photos/600/600?8',
      'https://picsum.photos/600/600?18',
      'https://picsum.photos/600/600?28',
    ],
    caption: 'City fragments',
    likes: 1760,
    comments: 39,
    commentList: PROFILE_COMMENTS,
    timestamp: '2d ago',
  },
  {
    id: 9,
    image: 'https://picsum.photos/600/600?9',
    type: 'video',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    caption: 'Infrared skyline',
    likes: 2043,
    comments: 51,
    commentList: PROFILE_COMMENTS,
    timestamp: '3d ago',
  },
  {
    id: 10,
    image: 'https://picsum.photos/600/600?10',
    type: 'image',
    caption: 'Broken symmetry',
    likes: 1120,
    comments: 24,
    commentList: PROFILE_COMMENTS,
    timestamp: '4d ago',
  },
  {
    id: 11,
    image: 'https://picsum.photos/600/600?11',
    type: 'image',
    caption: 'Night drive reflections',
    likes: 1870,
    comments: 42,
    commentList: PROFILE_COMMENTS,
    timestamp: '5d ago',
  },
  {
    id: 12,
    image: 'https://picsum.photos/600/600?12',
    type: 'image',
    caption: 'Monolith study',
    likes: 920,
    comments: 17,
    commentList: PROFILE_COMMENTS,
    timestamp: '6d ago',
  },
  {
    id: 13,
    image: 'https://picsum.photos/600/600?13',
    type: 'image',
    caption: 'Chrome memories',
    likes: 2430,
    comments: 73,
    commentList: PROFILE_COMMENTS,
    timestamp: '1w ago',
  },
]

export const PROFILE_SAVED_POSTS: Post[] = [
  {
    id: 21,
    image: 'https://picsum.photos/600/600?21',
    type: 'image',
    caption: 'Abstract color play',
    likes: 5432,
    comments: 234,
    commentList: PROFILE_COMMENTS,
    timestamp: '3d ago',
  },
  {
    id: 22,
    image: 'https://picsum.photos/600/600?22',
    type: 'image',
    caption: 'Camera kit flatlay',
    likes: 8765,
    comments: 567,
    commentList: PROFILE_COMMENTS,
    timestamp: '5d ago',
  },
  {
    id: 23,
    image: 'https://picsum.photos/600/600?23',
    type: 'carousel',
    images: [
      'https://picsum.photos/600/600?23',
      'https://picsum.photos/600/600?33',
      'https://picsum.photos/600/600?43',
    ],
    caption: 'Minimal interior series',
    likes: 12345,
    comments: 890,
    commentList: PROFILE_COMMENTS,
    timestamp: '1w ago',
  },
]

export const PROFILE_TAGGED_POSTS: Post[] = [
  {
    id: 31,
    image: 'https://picsum.photos/600/600?31',
    type: 'image',
    caption: 'City collab feature',
    likes: 980,
    comments: 62,
    commentList: PROFILE_COMMENTS,
    timestamp: '2d ago',
  },
  {
    id: 32,
    image: 'https://picsum.photos/600/600?32',
    type: 'carousel',
    images: [
      'https://picsum.photos/600/600?32',
      'https://picsum.photos/600/600?42',
    ],
    caption: 'Gallery night recap',
    likes: 1430,
    comments: 88,
    commentList: PROFILE_COMMENTS,
    timestamp: '4d ago',
  },
]
