import './globals.css'
import { StylesProvider } from './styles-provider'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Create Solito App',
  description: 'Generated by create Solito app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        suppressContentEditableWarning={true}
      >
     
        <StylesProvider>{children}</StylesProvider>
      </body>
    </html>
  )
}
